In [7]:
# Importando o módulo/pacote NumPy
import numpy as np

# Transposição e Reshaping de Arrays

In [8]:
# Criando Array

array1 = np.array([[65, 23, 19], [41, 87, 10]])
print(array1)

[[65 23 19]
 [41 87 10]]


In [9]:
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [10]:
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

### Broadcasting

In [11]:
# Criando Array

array2 = np.array([[33, 34, 35]])
print(array2)

[[33 34 35]]


In [12]:
array2.T

array([[33],
       [34],
       [35]])

In [13]:
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

### Transformando Matrizes em Vetores

In [14]:
# Criando Array

array3 = np.array([np.arange(1,6), np.arange(10,15)])
print(array3)
print(array3.ndim)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
2


In [15]:
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [16]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

### Operadores Lógicos

In [17]:
np.random.seed(100)
array4 = np.random.randint(1, 10, size = (4,4))
print(array4)

[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]]


In [18]:
np.any((array4 % 7) == 0)

False

In [19]:
np.all(array4 < 11)

True

In [20]:
# Retorne a linha onde o elemento de índice 1 na coluna seja maior que 2 e menor que 9
np.where(np.logical_and(array4[:,1] > 2, array4[:,1] < 9))

(array([2]),)

In [21]:
# Mesmo resultado que a linha anterior
np.intersect1d(np.where(array4[:,1] > 2), np.where(array4[:,1] < 9))

array([2])

In [22]:
array4[2]

array([6, 3, 3, 3])

### Reshaping e Ordenação de Arrays

In [23]:
# Criando Array

array5 = np.arange(1,16)
print(array5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
array5.ndim

1

In [25]:
array5.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
array7 = np.array([[3,2],[10,-1]])
print(array7)

[[ 3  2]
 [10 -1]]


In [27]:
# Ordenando por linhas
array7.sort(axis = 1)
print(array7)

[[ 2  3]
 [-1 10]]


In [28]:
array8 = np.array([[3,2],[10,-1]])
print(array8)

[[ 3  2]
 [10 -1]]


In [29]:
# Ordenando por colunas
array8.sort(axis = 0)
print(array8)

[[ 3 -1]
 [10  2]]
